Controller and service
Gobl1n2234/Attraction1 pull request #8
Opened 2021-11-12 04:19 UTC by Gobl1n223

2021-11-14 11:40 UTC, PavelAndryushenko requested changes
В этом PR соединено большое количество изменений, для каждого из которых нужен отдельный PR. В данном PR должны быть только изменения, связанные с ДТО и слоем контроллеров, изменения в сущностях, репозиториях и сервисов должны идти в отдельных PR.

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/controller/AttractionController.java
> +import liquibase.pro.packaged.A;
Зависимостей на Liquibase не должно быть в слое контроллеров

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/controller/AttractionController.java
> +    private AttractionService attractionService;
Лучше делать внедрение зависимостей через конструктор

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/dto/AttractionDTO.java
>      public AttractionDTO() {
Конструктора по умолчанию у ДТО быть не должно - все его атрибуты должны быть final и должны инициализроваться в all arguments contructor

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/dto/AttractionDTO.java
> +    }
Лучше такой маппинг Attraction в DTO делать не в самом ДТО, а в каком-то отдельном классе, единственной ответственностью которого будет маппинг Attraction в DTO и наоборот.
Посмотри, кстати, MapStruct - инструмент, который как раз позволяет генерировать такие мапперы.

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/entity/Attraction.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Изменения слоя сущностей не должны быть в этом PR - в этом PR должно быть только то, что связано с REST API

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/entity/City.java
> +    @JsonIgnore
Это аннотация Jackson - в сущностях ничего связанного с Jackson быть не должно - в Jackson маппятся только ДТО, а сущности в REST API нигде не должны быть задействованы

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/entity/Comment.java
> +    }
Если мы тут храним время создания записи, то лучше воспользоваться аннотацией @CreationTimestamp

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/entity/Rating.java
> +import javax.persistence.*;
Вот как раз было правильно - каждый класс нужно импортировать отдельно, через * не нужно это делать

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/entity/Rating.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Добавь, пожалуйста, в список задач такую задачу - Добавление использования графа сущностей для получения сущностей из БД.
От Eager будем избавляться таким образом.

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/java/com/example/app/attraction/request/RequestOptions.java
> +@Data
Если это ДТО, то лучше сделать его в Immutable Way - все атрибуты final, инициализируются только в конструкторе, для атрибутов есть только геттеры, без сеттеров

2021-11-14 11:40 UTC, PavelAndryushenko commented on src/main/resources/db/changelog/v-1.0/01.changeset-attraction-table.xml
> +            <column autoIncrement="true" name="id" type="bigint">
По-хорошему, скрипты Liquibase править нельзя - они уже закатились в БД, и таким образом, при следующем запуске, у Liquibase не сойдется контрольная сумма.
Для любый изменений в БД. нужно добавлять новые скрипты.

2021-11-16 00:21 UTC, Gobl1n223 commented on src/main/java/com/example/app/attraction/request/RequestOptions.java
> +@Data
Это не DTO, это просто обертка которая объединяет все принимаемы параметры в один

2021-11-16 13:07 UTC, PavelAndryushenko approved these changes

2021-11-16 17:55 UTC, merged